config/routes.rb
Rails.application.routes.draw do

  root to: 'dashing#dashboard'
  get 'dashing/dashboard'
  get 'billing_sites/:id/predictions' => 'billing_sites#show_predict_usage', as: :show_predictions_billing_site
  get 'billing_sites/:id/usage' => 'billing_sites#show_usage', as: :show_usage_billing_site
  post 'billing_sites/:id/usage' => 'billing_sites#show_usage'
  resources :ftp_servers


  # nested resources for testing purpose
  scope shallow_prefix: "billing_site" do
    resources :billing_sites do
      resources :retail_plans, shallow: true
    end
  end

#  resources :billing_sites

  resources :sites
  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'users/import' => 'users#upload_nem12'
  post 'users/import' => 'users#import_nem12'
  # user's show page
  get 'users/:id' => 'users#show', as: 'user', constraints: { id: /\d+/ }

  # resources :users, only: [:show],
  get 'users/profile' => 'users#show'

  resources :meters, except: [:new, :index, :show, :edit]

  # If no route matches for show, index, edit page
  get '/meters' => 'application#redirect_user'
  get '/meters/:id' => 'application#redirect_user'
  get '/meters/:id/edit' => 'application#redirect_user'

  # resources :retail_plans do
  #   collection do
  #     get :edit
  #   end
  # end

  resources :invoices do
    collection do
      get :predictNew
      post :select_date_period
      post :predict, to: "invoices#create_predicted_invoice"
      get :generateNew
      post :generate, to: "invoices#create_generated_invoice"
      get :import_invoice
      post :import, to: "invoices#create_imported_invoice"
      post :compare
    end
  end

  get 'meter_records/truncate' => 'meter_records#truncate'
  get 'meter_records/import' => 'meter_records#import_nem12'
  get 'meter_records/single_usage' => 'meter_records#single_usage'
  get 'meter_records/multiple_usage' => 'meter_records#multiple_usage'
  get 'meter_records/single_predicted_usage' => 'meter_records#single_predicted_usage'
  get 'meter_records/multiple_predicted_usage' => 'meter_records#multiple_predicted_usage'

  get 'meter_aggregations/truncate' => 'meter_aggregations#truncate'

  resources :meter_records, :meter_aggregations

  # duplicated resources
  # resources :meters

  post '/billing_sites/:id' => 'billing_sites#show'

end

app/models/retail_plan.rb
class RetailPlan < ActiveRecord::Base

  #List of all validations for Retail plan during both create and update
  validate :value_presence
  validates :discount, numericality: {less_than_or_equal_to: 1, greater_than_or_equal_to: 0}
  validate :date_clashes

  belongs_to :billing_site
  belongs_to :retailer

  # after using the gem 'active_record-acts_as'
  has_many :charge_factories, dependent: :destroy
  has_many :daily_usage_charges
  has_many :global_usage_charges
  has_many :metering_charges
  has_many :supply_charges
  has_many :certificate_charges
  has_many :capacity_charges
  has_many :invoices, dependent: :destroy

  accepts_nested_attributes_for :daily_usage_charges, update_only: true
  accepts_nested_attributes_for :global_usage_charges, update_only: true
  accepts_nested_attributes_for :metering_charges, update_only: true
  accepts_nested_attributes_for :supply_charges, update_only: true
  accepts_nested_attributes_for :charge_factories, update_only: true
  accepts_nested_attributes_for :certificate_charges, update_only: true
  accepts_nested_attributes_for :capacity_charges, update_only: true

  #Validation methods
  def value_presence
    if name.blank?
      logger.info "........------....... Name Blank"
      errors.add(:name, "Cannot be blank")
    end
  end

  #Validation methods
  def date_clashes
    if start_date > end_date
      logger.info "........------....... Start less than End date"
      errors.add(:start_date, "Cannot be later than the End date")
    end
  end


  # Assign Retail Plan ID to daily usage charges
  def daily_usage_charges
    DailyUsageCharge.where(retail_plan_id: self)
  end
  # Assign Retail Plan ID to global usage charges
  def global_usage_charges
    GlobalUsageCharge.where(retail_plan_id: self)
  end
  # Assign Retail Plan ID to metering charges
  def metering_charges
    MeteringCharge.where(retail_plan_id: self)
  end
  # Assign Retail Plan ID to supply charges
  def supply_charges
    SupplyCharge.where(retail_plan_id: self)
  end
  # Assign Retail Plan ID to certificate charges
  def certificate_charges
    CertificateCharge.where(retail_plan_id: self)
  end
  # Assign Retail Plan ID to capacity charges
  def capacity_charges
    CapacityCharge.where(retail_plan_id: self)
  end


  # Return daily time periods for prediction method(Start and end time of Daily usage charges of retail plans associated with the meter)
  def self.dailyTimePeriods meters
    dtp =[]

    #Assign the latest Retail Plan
    retail_plan = RetailPlan.last

    #Assign the daily usage charges of the latest retail plan
    @daily = retail_plan.daily_usage_charges
    @daily.each do |daily_usage|
      dtp << ( { :start_time => daily_usage.start_time, :end_time => daily_usage.end_time, :label => daily_usage.name})
    end
    return dtp.to_a
  end


  # Return daily time periods (Start and end time of Daily usage charges of retail plans)
  # Reloaded dailyTimePeriods without parameter
  # Return: [Hash(:start_time, value),Hash(:end_time, value)]
  def daily_time_periods
    daily_time_periods = []
    @daily_usage_charges = self.daily_usage_charges
    @daily_usage_charges.each do |daily_usage_charge|
      daily_time_periods << {start_time: daily_usage_charge.start_time, end_time: daily_usage_charge.end_time}
    end
    return daily_time_periods
  end


  # Daily time periods for Metering system
  def self.daily_time_periods meters
    #   Defining as a set guarantees unique values...
    daily_time_periods = Set.new []
    DailyUsageCharge.all.each do |duc|
      daily_time_periods.add ( { :start_time => duc.start_time, :end_time => duc.end_time, :label => duc.name } )
    end
    #   ... but return as array
    return daily_time_periods.to_a
  end


  # Returns an array containing the ChargeFactories used by this RetailPlan
  def chargefactories
    charge_factory_are_used = []
    self.charge_factories.each do |charge_factory|
      charge_factory_are_used << charge_factory
    end
    return charge_factory_are_used
  end


  # Returns an array of the meters that are used by this RetailPlan
  def meters
    meters_are_used = []
    self.billing_site.meters.each do |meter|
      meters_are_used << meter
    end
    return meters_are_used
  end


  # Returns an array of billing periods,
  # for which the system is able to provide predicted data
  def predictable_billing_periods
    time_periods = []
    #decide the increment time period
    if self.billing_interval == "Monthly"
      incrementBy = 1.month
    elsif self.billing_interval == "Quarterly"
      incrementBy = 3.months
    else
      return "No billing interval record!"
    end

    #get the first period of the predictable period list
    currentStartDate = self.invoices.where(actable_type: ImportedInvoice).last[:end_date] + 1.day
    currentEndDate = currentStartDate + incrementBy
    time_periods << {:start_date => currentStartDate, :end_date => currentEndDate}

    #calculate the end of the NEXT Financial year
    currentYear = currentStartDate.year
    eonfy = Date.new(currentYear,06,30)
    if (currentStartDate - 1.day).month <= 6
      eonfy = eonfy + 1.year
    else
      eonfy = eonfy + 2.year
    end

    #insert the remain periods of the predictable period 
    while  currentEndDate < eonfy
      currentStartDate = currentEndDate + 1.day
      currentEndDate = currentEndDate + incrementBy
      time_periods << {:start_date => currentStartDate, :end_date => currentEndDate}
    end

    return time_periods
 end
end

app/controllers/retail_plans_controller.rb
class RetailPlansController < ApplicationController

  # Index page for Retail Plans
  # GET index
  def index
    @billing_site = BillingSite.find(params[:billing_site_id])
    @retail_plans = @billing_site.retail_plans.order(:id)
  end


  # GET new
  def new
    @billing_site = BillingSite.find(params[:billing_site_id])
    @retail_plan = RetailPlan.new
  end


  #GET show
  def show
    @retail_plan = set_retail_plan

  end

  #POST edit
  def edit
    @retail_plan = set_retail_plan

  end


  # Create a new retail plan.
  #
  # POST create
  def create
    @retail_plan = RetailPlan.new(retail_plan_params)   #method for defining parameters, based on Rails 4.x rule
    billing_site_id = @retail_plan.billing_site_id
    count=0

    #Validate that no two retail plans have same time frame
    @all_retail_plan = RetailPlan.where(:billing_site_id => billing_site_id)
    @all_retail_plan.each do |rp|
      if  (@retail_plan.start_date >= rp.start_date && @retail_plan.start_date <= rp.end_date)
        count+=1
      end
    end

    @all_retail_plan.each do |rp|
      if ( @retail_plan.end_date >= rp.start_date && @retail_plan.end_date <=rp.end_date)
        count+=1
      end
    end

    # Generic Validations
    if count==0 && @retail_plan.start_date < @retail_plan.end_date
      if (@retail_plan.discount > 0 && @retail_plan.discount < 1)
        if(@retail_plan.name != nil)
          logger.info "-------------------#{@all_retail_plan.length}"
          if @retail_plan.save
            redirect_to billing_site_url(billing_site_id), notice: 'retail plan was successfully created.'
            #redirect_to billing_site_retail_plan_url(@retail_plan), notice: "Retail Plan Created Successfully"
          else
            redirect_to new_billing_site_retail_plan_path, alert: "Unsuccessful Creation of Retail Plan"
          end
        else
          redirect_to new_billing_site_retail_plan_path, alert: "Name of the Retail Plan shall not be empty"
        end

      else
        redirect_to new_billing_site_retail_plan_path, alert: "Discount should be greater than 0 and less than 1"
      end

    else
      redirect_to new_billing_site_retail_plan_path, alert: "Start and End date of retail plan clashes. Unsuccessful Creation of Retail Plan. "
    end
  end


  # Update action applies when user edits the fields of existing retail plan.
  # Find the RP by id, apply update and redirect to the retail page's index atfer displaying success message
  #
  # POST update
  def update
    @retail_plan = set_retail_plan
    billing_site_id = @retail_plan.billing_site_id
    count = 0

    # debug
    # charge_factories_params = params[:retail_plan][:charge_factories_attributes]
    daily_usage_charges_params = params[:retail_plan][:daily_usage_charges_attributes]
    global_usage_charges_params = params[:retail_plan][:global_usage_charges_attributes]
    metering_charges_params = params[:retail_plan][:metering_charges_attributes]
    supply_charges_params = params[:retail_plan][:supply_charges_attributes]
    capacity_charges_params = params[:retail_plan][:capacity_charges_attributes]
    certificate_charges_params = params[:retail_plan][:certificate_charges_attributes]

    daily_usage_charges_params.values.each do |attrs|
      DailyUsageCharge.find(attrs[:id]).update_attributes(attrs.slice!(:id))
    end
    global_usage_charges_params.values.each do |attrs|
      GlobalUsageCharge.find(attrs[:id]).update_attributes(attrs.slice!(:id))
    end

    # MeteringCharge and SupplyCharge do not have attributes
    metering_charges_params.values.each do |attrs|
      MeteringCharge.find(attrs[:id]).update_attributes(attrs.slice!(:id))
    end
    supply_charges_params.values.each do |attrs|
      SupplyCharge.find(attrs[:id]).update_attributes(attrs.slice!(:id))
    end

    #Capacity and Certificate Charges atrributes
    capacity_charges_params.values.each do |attrs|
      CapacityCharge.find(attrs[:id]).update_attributes(attrs.slice!(:id))
    end
    certificate_charges_params.values.each do |attrs|
      CertificateCharge.find(attrs[:id]).update_attributes(attrs.slice!(:id))
    end

    plan_params = params[:retail_plan].slice!(:charge_factories_attributes, :daily_usage_charges_attributes, :global_usage_charges_attributes, :metering_charges_attributes, :supply_charges_attributes, :capacity_charges_attributes, :certificate_charges_attributes)
    permitted = plan_params.permit!

    if @retail_plan.update_attributes(permitted)
      redirect_to billing_site_retail_plan_url(@retail_plan), notice: "Update Success"
    else
      render :edit, alert: "Update Failed"
    end
  end


  # Destroy selected retail plan and return to corresponding billing site
  #
  # POST destroy
  def destroy
    @retail_plan = RetailPlan.find(params[:id])
    billing_site_id = @retail_plan.billing_site_id
    @retail_plan.destroy
    redirect_to billing_site_url(billing_site_id), notice: "Retail Plan successfully destroyed"
  end


  # Required parameters for Retail Plan forms.
  def set_retail_plan
    @retail_plan_set= RetailPlan.find(params[:id])
  end


  # Allow particular (or all) parameters of Retail plan to be saved
  def retail_plan_params
    params.require(:retail_plan).permit!
  end
end

app/helpers/retail_plans_helper.rb
module RetailPlansHelper

  #similar to RP.find(params[:id]) used in show and edit. Just created in case we need to make use of current session's retail plan.
  #not used as of now.
  def current_retail_plan
    @current_retail_plan = RetailPlan.find(params[:id])
  end

end

app/views/retail_plans/_old_edit_form.html.erb
<%= simple_form_for @retail_plan do |f| %>
    <h3>Basic Information</h3>
    <%= f.input :name, label: 'Name of the Retail Plan', error: 'Name of the plan is necessary'%>
    <%= f.input :created, label: 'Date of Plan creation'%>
    <%= f.input :start_date, label: 'Start Date of Plan' %>
    <%= f.input :end_date, label: 'End date of Plan'%>
    <%= f.input :expected_expiry_date, label: 'Expected Expiry date of plan'%>
    <%= f.input :discount, label: 'Discount percentage'%>
    <%= f.error :name, id: 'name_error' %>

    <%= f.select :billing_site_id, BillingSite.all.collect{|u| [u.name, u.id]}, :prompt=>"Select a Billing Site" %>


    <!-- show properly but cannot be updated -->
    <% if false %>
    <h3>DailyUsageCharge</h3>
    <% @daily_usage_charges.each do |daily| %>
        <%= f.simple_fields_for daily.charge_factory do |c| %>
            <%= c.input :name, readonly: true %>
            <%= c.input :rate %>
         <% end %>
        <%= f.simple_fields_for daily do |c|%>
            <%= c.input :start_time %>
            <%= c.input :end_time %>
            <%= c.input :unit_of_measurement %>
        <% end %>
        <br>
    <% end %>

    <h3>GlobalUsageCharge</h3>
    <% @global_usage_charges.each do |global| %>
        <%= f.simple_fields_for global.charge_factory do |g| %>
            <%= g.input :name, readonly: true %>
            <%= g.input :rate %>
        <% end %>
        <%= f.simple_fields_for global do |g|%>
            <%= g.input :unit_of_measurement %>
        <% end %>
        <br>
    <% end %>

    <h3>MeteringCharge</h3>
    <% @metering_charges.each do |metering| %>
        <%= f.simple_fields_for metering.charge_factory do |m| %>
            <%= m.input :name, readonly: true %>
            <%= m.input :rate %>
        <% end %>
        <br>
    <% end %>

    <h3>SupplyCharge</h3>
    <% @supply_charges.each do |supply| %>
        <%= f.simple_fields_for supply.charge_factory do |s| %>
            <%= s.input :name, readonly: true %>
            <%= s.input :rate %>
        <% end %>
        <br>
    <% end %>

    <% end %>

    <!-- end -->

    <br>



    <%= f.simple_fields_for :charge_factories do |factory| %>
        <!-- daily usage charges -->
        <% if !factory.object.daily_usage_charges.blank? %>
            <%= factory.input :name, readonly: true %>
            <%= factory.simple_fields_for :daily_usage_charges do |d| %>
                <%= d.input :start_time %>
                <%= d.input :end_time %>
                <%= d.input :unit_of_measurement %>
            <% end %>
            <%= factory.input :rate %>
            <br>
        <% end %>

        <!-- global udage charges -->
        <% if !factory.object.global_usage_charges.blank? %>
            <%= factory.input :name, readonly: true %>
            <%= factory.simple_fields_for :global_usage_charges do |d| %>
                <%= d.input :unit_of_measurement %>
            <% end %>
            <%= factory.input :rate %>
            <br>
        <% end %>

        <!-- metering charges -->
        <% if !factory.object.metering_charges.blank? %>
            <%= factory.input :name, readonly: true %>
            <%= factory.simple_fields_for :metering_charges do |d| %>
                <!-- nothing here -->
            <% end %>
            <%= factory.input :rate %>
            <br>
        <% end %>

        <!-- supply charges -->
        <% if !factory.object.supply_charges.blank? %>
            <%= factory.input :name, readonly: true %>
            <%= factory.simple_fields_for :supply_charges do |d| %>
                <!-- nothing here -->
            <% end %>
            <%= factory.input :rate %>
            <br>
        <% end %>

    <% end %>

    <%= f.button :submit %>


<% end %>

app/views/retail_plans/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="row">
  <div class="col-md-12">
  	<p id="notice"><%= notice %></p>
    <h1 class="page-header">Update Retail Plan Details</h1>

  </div>


<%= render 'new_edit_form'  %>
</div>

app/views/retail_plans/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Welcome to Retail Plans</h1>
  </div>
</div>

<p>This is the landing page for Retail Plans.</p>
<!-- <p>Please click here to create new <a href="/retail_plans/new">Retail Plan</a> </p> -->

<!-- created by Charlene, testing so far -->
<p>Please click here to create
  <%= link_to 'New Retail Plan', new_billing_site_retail_plan_path(@billing_site) %> 
</p>


<table>
  <thead>
  <tr>
      <th>Retail Plan ID</th>
      <th>Retail Plan Name</th>
      <th>Created</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Edit</th>
      <th>Delete</th>
  </tr>
  </thead>
  <tbody>
  <% @retail_plans.each do |retail_plan| %>
  <tr>
      <td><%= retail_plan.id%></td>
    <!-- This line is for the link to retail plan, which is from Billing site-->
      <td><%= link_to retail_plan.name, billing_site_retail_plan_path(retail_plan) %></td>
      <td><%= retail_plan.start_date %></td>
      <td><%= retail_plan.end_date %></td>

      <td><%= link_to "edit", edit_billing_site_retail_plan_path(retail_plan)%></td>
      <td><%= link_to "Delete", billing_site_retail_plan_path(retail_plan), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }%></td>

  </tr>
  <% end %>
  </tbody>
</table>

<%if false%>
    <!-- From FrontEnd Code-->
    <td><%= link_to "edit", edit_retail_plan_path(retail_plan.id, :retail_plan => @retail_plan.billing_site_id)%></td>
    <td><%= link_to "Delete", retail_plan_path(retail_plan.id), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }%></td>

<%end%>

app/views/retail_plans/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">Create a new Retail Plan</h1>
  </div>


<%= link_to "   Back to #{@billing_site.name}", @billing_site %>

<%= render 'newForm' %>
</div>

app/views/retail_plans/old_show.html.erb
<h1><%= @retail_plan.name %></h1>

<div>
  <%= link_to "Back to Index", billing_site_retail_plans_path(@retail_plan.billing_site_id) %>
</div>

<p>Created: <%= @retail_plan.created %></p>
<p>Start Date: <%= @retail_plan.start_date%></p>
<p>End Date: <%= @retail_plan.end_date%></p>
<p>Expected Expiry Date: <%= @retail_plan.expected_expiry_date%></p>
<p>Discount: <%= @retail_plan.discount%></p>


<h3>DailyUsageCharge</h3>
<table>
  <thead>
  <th>Name</th>
  <th>Rate</th>

  <th> Unit Of Measurement</th>
  <th>Start Time</th>
  <th>End Time</th>
  </thead>

  <tbody>
  <% @retail_plan.charge_factories.each do |factory| %>
      <tr>
        <% factory.daily_usage_charges.each do |daily_charge| %>
            <td><%= factory.name %></td>
            <td><%= factory.rate %></td>
            <td><%= daily_charge.unit_of_measurement %></td>
            <td><%= daily_charge.start_time %></td>
            <td><%= daily_charge.end_time%></td>
        <% end %>
      </tr>
  <% end %>

  </tbody>
</table>

<h3>GlobalUsageCharge</h3>
<table>
  <thead>
  <th>Name</th>
  <th>Rate</th>

  <th> Unit Of Measurement</th>
  </thead>
  <tbody>
  <% @retail_plan.charge_factories.each do |factory| %>
      <tr>
        <% factory.global_usage_charges.each do |global_charge| %>
        <td><%= factory.name %></td>
        <td><%= factory.rate %></td>
        <td><%= global_charge.unit_of_measurement %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>


<h3>MeteringCharge</h3>
<table>
   <thead>
   <th>Name</th>
   <th>Rate</th>
   </thead>
   <tbody>
   <% @retail_plan.charge_factories.each do |factory| %>
   <tr>
     <% factory.metering_charges.each do |metering_charge| %>
       <td><%= factory.name %></td>
       <td><%= factory.rate %></td>
     <% end %>
   </tr>
   <% end %>
</tbody>
</table>

<h3>SupplyCharge</h3>
<table>
  <thead>
  <th>Name</th>
  <th>Rate</th>
  </thead>
  <tbody>
  <% @retail_plan.charge_factories.each do |factory| %>
      <tr>
        <% factory.supply_charges.each do |supply_chagrge| %>
        <td><%= factory.name %></td>
        <td><%= factory.rate %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/retail_plans/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header"><%= @retail_plan.name %></h1>
  </div>
</div>


<p><b>Start Date: </b><%= @retail_plan.start_date%></p>
<p><b>End Date: </b><%= @retail_plan.end_date%></p>
<p><b>Expected Expiry Date: </b><%= @retail_plan.expected_expiry_date%></p>
<p><b>Discount: </b><%= @retail_plan.discount%></p>

<div class="row">
  <div class="col-md-8">
    <h3>Daily Usage Charge</h3>
    <table class="table table-bordered table-hover">
      <thead class="active">
      <th>Name</th>
      <th>Unit Of Measurement</th>
      <th>Rate</th>
      <th>Start Time</th>
      <th>End Time</th>
      </thead>

      <tbody>
      <% @retail_plan.daily_usage_charges.each do |factory| %>
          <tr>
              <td><%= factory.name %></td>         
              <td><%= factory.unit_of_measurement %></td>
              <td><%= factory.rate %></td>
              <td><%= factory.start_time.strftime('%I:%M %p') %></td>
              <td><%= factory.end_time.strftime('%I:%M %p') %></td>  
          </tr>
      <% end %>

      </tbody>
    </table>

    <h3>Global Usage Charge</h3>
    <table class="table table-bordered table-hover">
      <thead>
      <th>Name</th>
      <th>Unit Of Measurement</th>
      <th>Rate</th>
      </thead>
      <tbody>
      <% @retail_plan.global_usage_charges.each do |factory| %>
          <tr>
              <td><%= factory.name %></td>
              <td><%= factory.unit_of_measurement %></td>
              <td><%= factory.rate %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <h3>Capacity Charge</h3>
    <table class="table table-bordered table-hover">
      <thead>
        <th>Name</th>
        <th>Unit Of Measurement</th>
        <th>Rate</th>
        <th>Period</th>
      </thead>
      <tbody>
      <% @retail_plan.capacity_charges.each do |factory| %>
          <tr>
              <td><%= factory.name %></td>
              <td><%= factory.unit_of_measurement %></td>
              <td><%= factory.rate %></td>
              <td><%= factory.period %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <h3>Certificate Charge</h3>
    <table class="table table-bordered table-hover">
      <thead>
        <th>Name</th>
        <th>Unit Of Measurement</th>
        <th>Rate</th>
      </thead>
      <tbody>
      <% @retail_plan.certificate_charges.each do |factory| %>
          <tr>
              <td><%= factory.name %></td>
              <td><%= factory.unit_of_measurement %></td>
              <td><%= factory.rate %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <h3>Metering Charge</h3>
    <table class="table table-bordered table-hover">
       <thead>
       <th>Name</th>
       <th>Rate</th>
       </thead>
       <tbody>
       <% @retail_plan.metering_charges.each do |factory| %>
       <tr>
           <td><%= factory.name %></td>
           <td><%= factory.rate %></td>
       </tr>
       <% end %>
    </tbody>
    </table>

    <h3>Supply Charge</h3>
    <table class="table table-bordered table-hover">
      <thead>
      <th>Name</th>
      <th>Rate</th>
      </thead>
      <tbody>
      <% @retail_plan.supply_charges.each do |factory| %>
          <tr>
              <td><%= factory.name %></td>
              <td><%= factory.rate %></td>
          </tr>
      <% end %>
      </tbody>
    </table>


    <!-- debug -->
    <% if false %>
    <h3>DailyUsageCharge</h3>
    <table>
      <thead>
      <th>Name</th>
      <th>Rate</th>

      <th> Unit Of Measurement</th>
      <th>Start Time</th>
      <th>End Time</th>
      </thead>

      <tbody>
      <% @retail_plan.charge_factories.each do |factory| %>
          <tr>
            <% if factory.specific.is_a?(DailyUsageCharge) %>
              <td><%= factory.name %></td>
              <td><%= factory.rate %></td>
              <td><%= factory.specific.unit_of_measurement %></td>
              <td><%= factory.specific.start_time %></td>
              <td><%= factory.specific.end_time%></td>
            <% end %>
          </tr>
      <% end %>

      </tbody>
    </table>

    <h3>GlobalUsageCharge</h3>
    <table>
      <thead>
      <th>Name</th>
      <th>Rate</th>

      <th> Unit Of Measurement</th>
      </thead>
      <tbody>
      <% @retail_plan.charge_factories.each do |factory| %>
          <tr>
            <% if factory.specific.is_a?(GlobalUsageCharge) %>
              <td><%= factory.name %></td>
              <td><%= factory.rate %></td>
              <td><%= factory.specific.unit_of_measurement %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>


    <h3>MeteringCharge</h3>
    <table>
       <thead>
       <th>Name</th>
       <th>Rate</th>
       </thead>
       <tbody>
       <% @retail_plan.charge_factories.each do |factory| %>
       <tr>
         <% if factory.specific.is_a?(MeteringCharge) %>
           <td><%= factory.name %></td>
           <td><%= factory.rate %></td>
         <% end %>
       </tr>
       <% end %>
    </tbody>
    </table>

    <h3>SupplyCharge</h3>
    <table>
      <thead>
      <th>Name</th>
      <th>Rate</th>
      </thead>
      <tbody>
      <% @retail_plan.charge_factories.each do |factory| %>
          <tr>
            <% if factory.specific.is_a?(SupplyCharge) %>
              <td><%= factory.name %></td>
              <td><%= factory.rate %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>



<%if false%>
    <!-- From Billing_2 - Go to index after creating a retail plan-->
<%= link_to "Back to Index", billing_site_retail_plans_path(@retail_plan.billing_site_id) %>
    <div>
      <%= link_to 'Back to your Billing Site', billing_sites_url%>
      </br>
    </div>
<%end%>

<% end %>
<!-- debug end -->