config/routes.rb
Rails.application.routes.draw do

  root to: 'dashing#dashboard'
  get 'dashing/dashboard'
  get 'billing_sites/:id/predictions' => 'billing_sites#show_predict_usage', as: :show_predictions_billing_site
  get 'billing_sites/:id/usage' => 'billing_sites#show_usage', as: :show_usage_billing_site
  post 'billing_sites/:id/usage' => 'billing_sites#show_usage'
  resources :ftp_servers


  # nested resources for testing purpose
  scope shallow_prefix: "billing_site" do
    resources :billing_sites do
      resources :retail_plans, shallow: true
    end
  end

#  resources :billing_sites

  resources :sites
  devise_for :users, controllers: { registrations: "users/registrations" }
  get 'users/import' => 'users#upload_nem12'
  post 'users/import' => 'users#import_nem12'
  # user's show page
  get 'users/:id' => 'users#show', as: 'user', constraints: { id: /\d+/ }

  # resources :users, only: [:show],
  get 'users/profile' => 'users#show'

  resources :meters, except: [:new, :index, :show, :edit]

  # If no route matches for show, index, edit page
  get '/meters' => 'application#redirect_user'
  get '/meters/:id' => 'application#redirect_user'
  get '/meters/:id/edit' => 'application#redirect_user'

  # resources :retail_plans do
  #   collection do
  #     get :edit
  #   end
  # end

  resources :invoices do
    collection do
      get :predictNew
      post :select_date_period
      post :predict, to: "invoices#create_predicted_invoice"
      get :generateNew
      post :generate, to: "invoices#create_generated_invoice"
      get :import_invoice
      post :import, to: "invoices#create_imported_invoice"
      post :compare
    end
  end

  get 'meter_records/truncate' => 'meter_records#truncate'
  get 'meter_records/import' => 'meter_records#import_nem12'
  get 'meter_records/single_usage' => 'meter_records#single_usage'
  get 'meter_records/multiple_usage' => 'meter_records#multiple_usage'
  get 'meter_records/single_predicted_usage' => 'meter_records#single_predicted_usage'
  get 'meter_records/multiple_predicted_usage' => 'meter_records#multiple_predicted_usage'

  get 'meter_aggregations/truncate' => 'meter_aggregations#truncate'

  resources :meter_records, :meter_aggregations

  # duplicated resources
  # resources :meters

  post '/billing_sites/:id' => 'billing_sites#show'

end

app/models/site.rb
class Site < ActiveRecord::Base

  belongs_to :user
  has_many :billing_sites, dependent: :destroy
  has_many :meters, through: :billing_sites

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    # order by ID
    @sites = current_user.sites.order(:id)
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @billing_sites = @site.billing_sites.order(:id)
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)
    @all_sites = current_user.sites
    count = 0

    #two sites for the same user shall not have similar names
    @all_sites.each do |value|
      if value.name == @site.name
        count+=1
      end
    end

    respond_to do |format|
      if !@site.name.blank?
        if count==0
          if @site.save
            format.html { redirect_to @site, notice: 'Site was successfully created.' }
            format.json { render :show, status: :created, location: @site }
          else
            format.html { render :new }
            format.json { render json: @site.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to @site, alert: "Site already exists. Try again" }
          format.json { render json: @site.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @site, alert: "Site name Cannot be empty. Try again" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :address1, :address2, :user_id, :created)
    end

    def set_user
      if params[:id]
        @user = User.find(params[:id])
      else
        @user = current_user
      end
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<div class="modal-body">
<%= simple_form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="field">
    <%# f.label :name %><!-- <br> -->
    <%# f.text_field :name %>
    <%= f.input :name %>
  </div>
  <div class="field">
    <%# f.label :address1 %><!-- <br> -->
    <%# f.text_field :address1 %>
    <%= f.input :address1 %>
  </div>
  <div class="field">
    <%# f.label :address2 %><!-- <br> -->
    <%# f.text_field :address2 %>
    <%= f.input :address2 %>
  </div>
  <div class="field">
    <%# f.label :created %><!-- <br> -->
    <%# f.datetime_select :created %>
    <%= f.input :created %>
  </div>
</div>
<div class="modal-footer">
  <div class="actions">
    <%# f.submit %>
    <%= f.button :submit, :class =>"btn btn-primary" %>
    <%# link_to "Cancel", :back, {:class=>"btn btn-default"} %>
    <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button> -->
  </div>
</div>
<% end %>

app/views/sites/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">Editing <%= @site.name %></h1>
  </div>
</div>

<%= render 'form' %>

<% if false %>
<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>
<% end %>

app/views/sites/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">Site List</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">

        <table class="table table-hover">
          <thead>
          <tr>
            <th>Name</th>
            <th>Address1</th>
            <th>Address2</th>
            <th>Created</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @sites.each do |site| %>
              <tr>
                <td class="site"><%= link_to site.name, site %></td>
                <td><%= site.address1 %></td>
                <td><%= site.address2 %></td>
                <td><%= site.created.strftime("%B %d, %Y") %></td>
                <td>
                  <%# link_to "Edit", edit_site_path(site), :class => "btn btn-success btn-xs", "data-toggle" => "modal", "data-target" => ".bs-example-modal-lg" %>   

                  <!-- Button trigger modal -->
                  <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#editSite_<%= site.id %>" >Edit</button>

                  <!-- editSite Modal -->
                  <div id="editSite_<%= site.id %>" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="editSiteModalLabel">
                    <div class="modal-dialog modal-lg">
                       <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title">Editing <%= site.name %></h4>
                        </div>

                        <%= render 'form', :@site => site %>

                      </div>
                    </div>
                  </div>

                  <%= link_to 'Delete', site, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %>

                </td>
              </tr>

          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



<br>
<%# link_to "New sites", new_site_path, :class => "btn btn-primary", "data-toggle" => "modal", "data-target" => ".bs-example-modal-lg" %>
<!-- changed by Charlene -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newSite">Create a new site</button>
<!--<a data-toggle="modal" class="btn btn-info" href="#{new_billing_site_path}" data-target=".bs-example-modal-lg">Click me !</a>-->
<div id="newSite" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <!-- changed by Charlene -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Site</h4>
      </div>

      <%= render partial: 'form', locals: {:@site => Site.new} %>

    </div>
  </div>
</div>


<script type="text/javascript">
  $('td.site a').on("click", function(e){
    e.preventDefault();
      
    document.location = $(this).attr("href");
  });
</script>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
    <%# link_to "Sites /", sites_path %>
    <%# @site.name %>
      <ol class="breadcrumb">
          <li><%= link_to "Sites", sites_path %></li>
          <li class="active"><%= @site.name %></li>
        </ol>
    </div>
  </div>
</div>
<div class="row">  
  <div class="col-md-4">
    <p>
      <strong>Name:</strong>
      <%= @site.name %>
    </p>

    <p>
      <strong>Address1:</strong>
      <%= @site.address1 %>
    </p>

    <p>
      <strong>Address2:</strong>
      <%= @site.address2 %>
    </p>

    <p>
      <strong>Created:</strong>
      <%= @site.created.strftime("%B %d, %Y") %>
    </p>

    <!-- Button trigger modal -->
    <%# link_to "Edit", edit_site_path(@site), :class => "btn btn-success" %>
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#editSite">Edit</button>

    <!-- Modal -->
    <div id="editSite" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="editSiteModalLabel">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Editing <%= @site.name %></h4>
          </div>

          <%= render 'form', site: @site %>

        </div>
      </div>
    </div>

  </div>
  <div class="col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading">

        <!-- Button trigger modal -->
        <%# link_to "New", new_billing_site_path(:site_id => @site.id),
                    :class =>"btn btn-default pull-right", "data-toggle" => "modal", "data-target" => "#newBillingSite" %>
        <button type="button" class="btn btn-default pull-right" data-toggle="modal" data-target="#newBillingSite">New</button>

        <!-- Modal -->
        <div id="newBillingSite" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" style="color:black">New Billing Site</h4>
              </div>

              <%= render partial: 'billing_sites/form', locals: { :@billing_site => BillingSite.new, :site_id => @site.id } %>

            </div>
          </div>
        </div>

        <h4>Billing Sites</h4>

      </div>
      <div class="panel-body">

        <table class="table table-hover">
          <thead>
          <tr>
            <th>Name</th>
            <th>Created</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% @billing_sites.each do |billing_site| %>
              <tr>
                <td class="billing_site"><%= link_to billing_site.name, billing_site %></td>
                <td><%= billing_site.created%></td>

                <!-- Button trigger modal -->
                <td>
                  <%# link_to 'Edit', edit_billing_site_path(billing_site, :site_id => @site.id), :class => "btn btn-success btn-xs", "data-toggle" => "modal", "data-target" => ".bs-example-modal-sm" %>
                  <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#editBillingSite_<%= billing_site.id %>">Edit</button>
                </td>
                <!-- Modal -->
                <div id="editBillingSite_<%= billing_site.id %>" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="editBillingSiteModalLabel">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Editing <%= billing_site.name %></h4>
                      </div>

                      <%= render partial: 'billing_sites/form', locals: { :@billing_site => billing_site, :site_id => @site.id } %>
                      <%# debug billing_site %>

                    </div>
                  </div>
                </div>

                <td><%= link_to 'Delete', billing_site, method: :delete, data: { confirm: 'Are you sure?' },
                                :class => "btn btn-danger btn-xs"%></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('div.page-header a').on("click", function(e){
    e.preventDefault();
      
    document.location = $(this).attr("href");
  });
  $('td.billing_site a').on("click", function(e){
    e.preventDefault();
      
    document.location = $(this).attr("href");
  });
</script>